version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mongo-db
    environment:
      DATABASE_URL: mongodb://smajwloo:password@mongo-db:27017
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
  mongo-db:
    image: mongo:latest
    volumes:
      - end-project-volume:/database-files
    restart: always
    expose: ["27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: smajwloo
      MONGO_INITDB_ROOT_PASSWORD: password
volumes:
  end-project-volume: