name: jest coverage report
on:
  push:
    paths: 
      - 'api/**'
  pull_request:
    branches: [ main ]
    
jobs:
    coverage:
        defaults:
          run:
            working-directory: './api'
        
        runs-on: ubuntu-latest
        
        steps:
          - name: Jest coverage report
            uses: ArtiomTr/jest-coverage-report-action@v2.2.1-rc.0
            with:
              working-directory: 'api'
